# Generated by Django 3.2.9 on 2021-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20211104_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='script_1',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='script_title_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
