# Generated by Django 3.2.7 on 2021-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20211104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gist_1',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='gist_title_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
