# Generated by Django 3.2.7 on 2021-11-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_auto_20211105_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='gist_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
