# Generated by Django 3.2.7 on 2021-11-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_article_new_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_edited',
        ),
    ]
