# Generated by Django 3.2.7 on 2021-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_alter_article_gist_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='script_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
