# Generated by Django 3.2.7 on 2021-11-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0006_remove_article_date_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='new_date_added',
        ),
    ]
