# Generated by Django 3.2.7 on 2021-11-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0006_article_script_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='script_2',
        ),
    ]
