# Generated by Django 3.2.7 on 2021-11-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0007_remove_article_new_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='codepen_data_slug_hash_1',
            new_name='codepen_data_slug_hash',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='codepen_title_1',
            new_name='codepen_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='gist_1',
            new_name='gist',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='gist_title_1',
            new_name='gist_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='script_1',
            new_name='jsconsole_permalink',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='script_title_1',
            new_name='jsconsole_title',
        ),
    ]
