# Generated by Django 3.2.7 on 2021-11-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creationdate',
            name='date_last_edited',
        ),
    ]
