# Generated by Django 3.2.7 on 2021-11-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_creationdate_date_last_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creationdate',
            old_name='date_created',
            new_name='this_date_created',
        ),
    ]
